deployment:
  tasks:
    - git fetch origin
    - git reset --hard origin/main
    - git clean -fd
    - cp -R * $DEPLOYPATH
    - rm -rf .git
    - rm -f .gitignore
    - rm -f .cpanel.yml
    - rm -f .htaccess
  environment:
    DEPLOYPATH: /home/eitech/public_html/
