build:
  tasks:
    - /bin/cp -R * /home/eitech/public_html/
    - /bin/chmod -R 755 /home/eitech/public_html/
    - /bin/chown -R eitech:eitech /home/eitech/public_html/
  environment:
    DEPLOYPATH: /home/eitech/public_html/
